name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: 0.15.4
  cloud_firestore: 0.13.3
  firebase_core: 0.4.4
  dio: ^3.0.0
  logging: ^0.11.0
  flutter_advanced_networkimage: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

